#!/usr/bin/env python


from gradelib import *

runner = Runner()

@test(0, "build pk")
def test_build_pk():
	runner.run_build_pk()
	
@test(0, "running app3 m2048")
def test_app3_m2048():
	runner.run_app('app2')

@test(10, "test3_m2048", parent='app3')
def test_lab3_m2048():
    runner.match("mem_size = 0x80000000")

@test(0, "running app3 m1024")
def test_app3_m1024():
	runner.run_app('app2', mem = '1024')

@test(10, "test3_m1024", parent='app3')
def test_lab3_m1024():
    runner.match("mem_size = 0x40000000")

show_grade()	

