#!/usr/bin/env python
#coding:utf-8

from gradelib import *

runner = Runner()

@test(0, "build pk")
def test_build_pk():
	runner.run_build_pk()
	
@test(0, "running app5_1")
def test_app4():
	runner.run_app('app5_1')

@test(20, "test fork", parent='app5_1')
def test_fork():
    runner.match("print proc this is child process;my pid = 2")
    runner.match("print proc a=9")
    runner.match("print proc this is child process;my pid = 3")
    runner.match("print proc a=6")
    runner.match("print proc this is farther process;my pid = 2")
    runner.match("print proc a=5")
    runner.match("print proc this is farther process;my pid = 1")
    runner.match("print proc a=8")
    runner.match("print proc this is child process;my pid = 4")
    runner.match("print proc a=5")
    runner.match("print proc this is farther process;my pid = 1")
    runner.match("print proc a=4")


show_grade()	

